### PR TITLE
Minor tweaks

### PR DESCRIPTION
**Pull request by MrBrain295**

### CODE REVIEW

**Comment by Richienb** [comment]
I don't intend to strictly follow PEP8. There are only 3 changes which I think still have merit though:

- Aligning `and` operators at the start
- Adding a newline for the "typed" keyword
- Removing the indention on the blank line

**Comment by MrBrain295** [comment]
@Richienb done!

**Comment by Richienb** [comment]
I don't want the tabs to be replaced with spaces

**Comment by MrBrain295** [comment]
done

**Comment by Richienb** [comment]
Not done yet. Check the diff.

**Comment by MrBrain295** [comment]
done

**Comment by Richienb** [comment]
Not done yet

image

**Comment by MrBrain295** [comment]
done

**Pull request merged**
